---
- name: Install MySQL
  apt: name={{ item }} state=present
  with_items:
   - mysql-server-5.6
   - mytop 
   - python-mysqldb

- name: Backup MySQL Standard Config
  command: /bin/cp /etc/mysql/my.cnf /etc/mysql/my.cnf.org creates=/etc/mysql/my.cnf.org

- name: Replace MySQL Configuration 
  template: src=my.cnf.j2 dest=/etc/mysql/my.cnf
  notify: restart mysql

- name: Create ROOT User
  mysql_user: name={{ mysql_root_user }}
              password={{ mysql_root_pass }}
              priv=*.*:ALL,GRANT
              host={{ mysql_db_host }}
              state=present
  
- name: Write Users .my.cnf
  template: src=my.user.cnf.j2
            dest=~/.my.cnf
            mode=0600

- name: Create APP Database
  mysql_db: name={{ mysql_db_name }}
            state=present
  
- name: Create APP User
  mysql_user: name={{ mysql_db_user }}
              password={{ mysql_db_pw }}
              priv={{ mysql_db_name }}.*:ALL
              host={{ mysql_db_host }}
              state=present

