---
- name: Install MySQL
  apt: name={{ item }} state=present
  with_items:
   - mysql-server-5.5
   - mytop 
   - python-mysqldb
  
- name: Customize MySQL Configuration 
  template: src=mzl.my.cnf dest=/etc/mysql/my.cnf
  notify: restart mysql

- name: Create Database  
  mysql_db: name={{ mzl_db_database }} state=present
  
- name: Create User
  mysql_user: name={{ mzl_db_user }} password={{ mzl_db_pw }} priv={{ mzl_db_database }}.*:ALL host='{{ mzl_db_host }}' state=present